In [1]:
import numpy as np

In [32]:
a_array=np.arange(10)
b_array=np.random.choice(a_array,1)[0]
b_array

1

In [116]:
np.random.randint(0,5)
np.array([[4,3]])[0,1]
np.array([0,np.random.randint(0,5)])[0]

0

In [220]:
bomb_positions = [(3,3),(3,4)]
print(bomb_positions)
gold_positions = [(4,3)]
terminal_states = np.array(bomb_positions+gold_positions)
terminal_states

[(3, 3), (3, 4)]


array([[3, 3],
       [3, 4],
       [4, 3]])

In [237]:
len(bomb_positions)

2

In [242]:
grid=np.zeros([5,5])
for i in bomb_positions:
    grid[i] = -10
for j in gold_positions:
    grid[j] = 10
print(grid)

[[  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0. -10. -10.]
 [  0.   0.   0.  10.   0.]]


In [283]:
grid[(2,3)]

0.0

In [285]:
posicion=np.array([0,3])
posicion

array([0, 3])

In [290]:
grid[tuple(posicion)]

0.0

In [ ]:
terminal_states=np.array

In [5]:
a=("uno","dos","tres")
b=zip(a,range(3))
for i,j in b:
    print(i,j)

uno 0
dos 1
tres 2


In [3]:
9%5

4

In [33]:
a=22
a//=2
a//=2
a

5

In [38]:
import numpy as np
a=np.array([0,0,0])

In [39]:
posiciones=[1,2] 

In [41]:
a[posiciones]=1
a


array([0, 1, 1])

In [18]:
a=np.array([[[1,1,1],[1,1,1],[1,1,1]],[[2,2,2],[2,2,2],[2,2,2]]])
a[1]

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [19]:
a.shape

(2, 3, 3)

In [28]:
estados = np.arange(25)*np.ones((3,25))
for estado in estados:
    print(estado)
18%18

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24.]


0

In [37]:
12+25
37%25

12

In [43]:
26%25

1

In [1]:
1//25

0

In [45]:
50//25

2

In [46]:
50%25

0

In [47]:
(12+50)%25

12

In [48]:
4%5

4