In [1]:
import numpy as np

In [32]:
a_array=np.arange(10)
b_array=np.random.choice(a_array,1)[0]
b_array

1

In [116]:
np.random.randint(0,5)
np.array([[4,3]])[0,1]
np.array([0,np.random.randint(0,5)])[0]

0

In [220]:
bomb_positions = [(3,3),(3,4)]
print(bomb_positions)
gold_positions = [(4,3)]
terminal_states = np.array(bomb_positions+gold_positions)
terminal_states

[(3, 3), (3, 4)]


array([[3, 3],
       [3, 4],
       [4, 3]])

In [237]:
len(bomb_positions)

2

In [242]:
grid=np.zeros([5,5])
for i in bomb_positions:
    grid[i] = -10
for j in gold_positions:
    grid[j] = 10
print(grid)

[[  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0. -10. -10.]
 [  0.   0.   0.  10.   0.]]


In [283]:
grid[(2,3)]

0.0

In [285]:
posicion=np.array([0,3])
posicion

array([0, 3])

In [290]:
grid[tuple(posicion)]

0.0

In [ ]:
terminal_states=np.array