In [1]:
import numpy as np

In [32]:
a_array=np.arange(10)
b_array=np.random.choice(a_array,1)[0]
b_array

1

In [116]:
np.random.randint(0,5)
np.array([[4,3]])[0,1]
np.array([0,np.random.randint(0,5)])[0]

0

In [220]:
bomb_positions = [(3,3),(3,4)]
print(bomb_positions)
gold_positions = [(4,3)]
terminal_states = np.array(bomb_positions+gold_positions)
terminal_states

[(3, 3), (3, 4)]


array([[3, 3],
       [3, 4],
       [4, 3]])

In [237]:
len(bomb_positions)

2

In [242]:
grid=np.zeros([5,5])
for i in bomb_positions:
    grid[i] = -10
for j in gold_positions:
    grid[j] = 10
print(grid)

[[  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0. -10. -10.]
 [  0.   0.   0.  10.   0.]]


In [283]:
grid[(2,3)]

0.0

In [285]:
posicion=np.array([0,3])
posicion

array([0, 3])

In [290]:
grid[tuple(posicion)]

0.0

In [ ]:
terminal_states=np.array

In [5]:
a=("uno","dos","tres")
b=zip(a,range(3))
for i,j in b:
    print(i,j)

uno 0
dos 1
tres 2


In [3]:
9%5

4

In [33]:
a=22
a//=2
a//=2
a

5

In [38]:
import numpy as np
a=np.array([0,0,0])

In [39]:
posiciones=[1,2] 

In [41]:
a[posiciones]=1
a


array([0, 1, 1])

In [18]:
a=np.array([[[1,1,1],[1,1,1],[1,1,1]],[[2,2,2],[2,2,2],[2,2,2]]])
a[1]

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [19]:
a.shape

(2, 3, 3)

In [28]:
estados = np.arange(25)*np.ones((3,25))
for estado in estados:
    print(estado)
18%18

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24.]


0

In [37]:
12+25
37%25

12

In [43]:
26%25

1

In [1]:
1//25

0

In [45]:
50//25

2

In [46]:
50%25

0

In [47]:
(12+50)%25

12

In [48]:
4%5

4

In [ ]:
def init_epsilon_policy(n_actions):
    policy={
        (a, b, c, d): {k: 1/n_actions for k in range(9)}
        for a in range(1, 18)
        for b in range(1, 14)
        for c in range(-10, 11)
        for d in range(-10, 11)
    }
    return policy
d=init_epsilon_policy(9)

In [ ]:

import numpy as np
a=np.array(list(d[(1,1,0,0)].values()))
b=np.arange(9)
np.random.choice(b, p=a)

7

In [46]:
for action in d[(1,1,1,2)].keys():
    print(action)

0
1
2
3
4
5
6
7
8


In [ ]:
import numpy as np
a= np.linspace(-6,4,100)

array([-6.        , -5.8989899 , -5.7979798 , -5.6969697 , -5.5959596 ,
       -5.49494949, -5.39393939, -5.29292929, -5.19191919, -5.09090909,
       -4.98989899, -4.88888889, -4.78787879, -4.68686869, -4.58585859,
       -4.48484848, -4.38383838, -4.28282828, -4.18181818, -4.08080808,
       -3.97979798, -3.87878788, -3.77777778, -3.67676768, -3.57575758,
       -3.47474747, -3.37373737, -3.27272727, -3.17171717, -3.07070707,
       -2.96969697, -2.86868687, -2.76767677, -2.66666667, -2.56565657,
       -2.46464646, -2.36363636, -2.26262626, -2.16161616, -2.06060606,
       -1.95959596, -1.85858586, -1.75757576, -1.65656566, -1.55555556,
       -1.45454545, -1.35353535, -1.25252525, -1.15151515, -1.05050505,
       -0.94949495, -0.84848485, -0.74747475, -0.64646465, -0.54545455,
       -0.44444444, -0.34343434, -0.24242424, -0.14141414, -0.04040404,
        0.06060606,  0.16161616,  0.26262626,  0.36363636,  0.46464646,
        0.56565657,  0.66666667,  0.76767677,  0.86868687,  0.96

In [ ]:
import numpy as np
def create_q_table():
    q = {
        (a, b, c, d): {k: 0 for k in range(9)}
        for a in range(1, 40)
        for b in range(1, 40)
        for c in range(-10, 11)
        for d in range(-10, 11)
    }
    return q
q= create_q_table()
keys= q.keys()
max(q[(1,1,1,1)], keys)

TypeError: '>' not supported between instances of 'dict_keys' and 'dict'

In [ ]:
# from tensorflow.keras.applications import EfficientNetB0
# from tensorflow.keras.applications import VGG16
from tensorflow.keras.applications import ResNet50

PT_conv_base = ResNet50(
    include_top=False,
    weights="imagenet",
    input_shape=(128,128,3))
for layer in PT_conv_base.layers: #Freeze all layers except conv5 (last ones)
    if "conv5" in layer.name:
      layer.trainable = True
    else:
      layer.trainable = False
# PT_conv_base.summary()
pt = PT_conv_base.output

modb_mlp0_age = Dense(512,activation = "relu") (pt)
modb_mlp1_age = Dense(1,activation = "softmax") (modb_mlp0_age)

modb_mlp0_gender = Dense(512,activation = "relu") (pt)
modb_mlp1_gender = Dense(1,activation = "softmax") (modb_mlp0_gender)

modelB=keras.Model(inputs=PT_conv_base.input, outputs=[modb_mlp1_age,modb_mlp1_gender])

In [2]:
def prueba():
    return 1,2,3,4
a,b,_,_=prueba()