# Reinforcement Learning
## Formative Assessment: Value Iteration
In this formative exercise, you will implement the Value Iteration algorithm to compute an optimal policy for three different (but closely related) Markov Decision Processes. For your reference, the pseudo-code for the Value Iteration algorithm is reproduced below from the textbook (Reinforcement Learning, Sutton & Barto, 2018, pp. 83).

<img src="images/value_iteration.png" style="width: 800px;"/>

Please note the following about the pseudo-code: The set $\mathcal{S}$ contains all non-terminal states, whereas $\mathcal{S}^+$ is the set of all states (terminal and non-terminal). The symbol $r$ represents the immediate reward on transition from state $s$ to the next state $s'$ via action $a$. 

<img src="images/bombs and gold numbers.png" style="width: 320px;" align="left" caption="Figure 1"/>

The two problems you will solve use variants of the gridworld environment shown on the left. You should be familiar with this kind of environment from the content you have seen so far in this unit. The grid squares in the figure are numbered as shown. In all exercises, the following are true: 

**Actions available:** The agent has four possible actions in each grid square. These are *west*, *north*, *south*, and *east*. If the direction of movement is blocked by a wall (for example, if the agent executes action south in grid square 1), the agent remains in the same grid square. 

**Collecting gold:** On its first arrival at a grid square that contains gold (from a neighbouring grid square), the agent collects the gold. Note that, in order to collect the gold, the agent needs to transition into the grid square (containing the gold) from a different grid square.

**Hitting the bomb:** On arrival at a grid square that contains a bomb (from a neighbouring grid square), the agent activates the bomb. 

**Terminal states:** The game terminates when **all** gold is collected or when the bomb is activated. In Exercises 1 and 2, you can define terminal states to be grid squares 18 and 23. In Exercise 3, you will need to define terminal state(s) differently.


### Instructions ###
Set parameter $\theta$ to $1 \times 10 ^{-10}$. You can express that as `1e-10` in Python. 

Set all initial state values $V(s)$ to zero.

Do not use discounting (that is, set $\gamma=1$).

Use the following reward function: $-1$ for each navigation action (including when the action results in hitting the wall), an additional $+10$ for collecting each piece of gold, and an additional $-10$ for activating the bomb. For example, the immediate reward for transitioning into a square with gold (from a neighbouring grid square) is $-1 + 10 = +9$. 

## Exercise 1: Deterministic Environment (0 Marks)

In this exercise, the agent is able to move in the intended direction with certainty. For example, if it executes action _north_ in grid square 0, it will transition to grid square 5 with probability 1. In other words, we have a deterministic environment.

Compute the optimal policy using Value Iteration. 

Your need to produce two one-dimensional numpy arrays with names `policy` and `v`. Both arrays should have a length of 25, with the element at index $i$ representing grid cell $i$ (see figure above). Both arrays should be accessible in the "solution cell" below!

The array `policy` should be a numpy array of strings that specifies an optimal action at each grid location. Please use the abbreviations `"n"`, `"e"`, `"s"`, and `"w"` for the four actions. As an example, the value of `policy` at index `0` needs to give `"n"`, if _north_ is an optimal action in cell 0. The policy for a terminal state can be any action. If there are multiple optimal actions from a state, any optimal action will be considered as a correct answer. 

The array `v` should be an array of floats that contains the expected return at each grid square (that is, the state value under the optimal policy).

In [3]:
import numpy as np
theta = 1e-10
v = np.zeros(25,dtype=float)
policy = np.full(25, "n", dtype=str)
rewards = np.full(25,-1,dtype=float)
rewards[23] = 9
rewards[18] = -11
posible_actions = ["n", "e", "s", "w"]
prob_moving_corr = 1
gamma = 1
delta=np.inf
while delta>=theta:
    delta=0
    for state in range(25):
        if state != 18 and state != 23:
            old_v = v[state]
            max_v = -np.inf
            for action in posible_actions:
                if action == "n" and state < 20:
                    new_state = state + 5
                elif action == "e" and state % 5 < 4:
                    new_state = state + 1
                elif action == "s" and state > 4:
                    new_state = state - 5
                elif action == "w" and state % 5 > 0:
                    new_state = state - 1

                value = prob_moving_corr * (rewards[new_state]+ gamma* v[new_state])
                if value > max_v:
                    max_v = value
                    policy[state] = action
                    v[state] = value
            delta = max(delta, np.abs(old_v - v[state]))
print(values)
print(policy)



[3. 4. 5. 4. 5. 4. 5. 6. 5. 6. 5. 6. 7. 6. 7. 6. 7. 8. 0. 8. 7. 8. 9. 0.
 9.]
['n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'e' 'n' 'n' 'n' 'n'
 'n' 'n' 'e' 'e' 'e' 'n' 'w']


In [ ]:
# Please write your code for Exercise 1 in this cell or in as many cells as you want ABOVE this cell.
# Your code should compute the values of policy and v from scratch when this cell is executed, 
# using the value iteration algorithm.

# YOUR CODE HERE


**Example Test Cell**

In the code cell below, we have provided an example of the type of test code that we will use to mark your work. In these tests, we first check that your `policy` and `v` variables are of the correct type, and then check that their values match the solution. For the remaining exercises, the answers will be hidden from you until the model answers are released.

In [5]:
# DO NOT DELETE OR MODIFY THIS CELL!
# Your code for Exercise 1 is tested here.

import numpy as np

# We're giving you the solution values for Exercise 1, but not telling you how to compute them!
solution_values = [3.0, 4.0, 5.0, 4.0, 5.0,
                   4.0, 5.0, 6.0, 5.0, 6.0,
                   5.0, 6.0, 7.0, 6.0, 7.0,
                   6.0, 7.0, 8.0, 0.0, 8.0,
                   7.0, 8.0, 9.0, 0.0, 9.0]
solution_values = np.array(solution_values)

# We're giving you the solution policy for Exercise 1, but not telling you how to compute it!
solution_policy = [
                   'n', 'n', 'n', 'n', 'n',
                   'n', 'n', 'n', 'n', 'n',
                   'n', 'n', 'n', 'e', 'n',
                   'n', 'n', 'n', 'n', 'n',
                   'e', 'e', 'e', 'n', 'w',]
solution_policy = np.array(solution_policy)

# Check that policy and v are numpy arrays.
assert(isinstance(policy, np.ndarray))
assert(isinstance(v, np.ndarray))

# Check correct shapes of numpy arrays.
assert(policy.shape == (25, ))
assert(v.shape == (25, ))

# Check whether the numpy arrays have the correct data types.
assert(np.issubdtype(policy.dtype, np.str_)) # policy.dtype should be '<U1'
assert(np.issubdtype(v.dtype, np.float64))

# Check whether policy contains only "n", "w", "s", or "e" values.
assert(np.all(np.isin(policy, np.array(["n", "w", "s", "e"]))))

# Print student's solution and true solution for easier comparison / spotting of errors.
print("Student's policy:")
print(np.flip(policy.reshape((5, 5)), 0))
print("Solution policy:")
print(np.flip(solution_policy.reshape((5, 5)), 0))
print("\n")
print("Student's v:")
print(np.flip(v.reshape((5, 5)), 0))
print("Solution v:")
print(np.flip(solution_values.reshape((5, 5)), 0))

# Compare state values for non-terminal states.
states_to_check = np.delete(np.arange(25), np.array([18, 23]))
incorrect_error_message = "[Marking Advice] State values incorrect."
np.testing.assert_array_almost_equal(v[states_to_check], solution_values[states_to_check], decimal=3, err_msg=incorrect_error_message)

# Compare policy (only on states that have a single optimal direction).
states_to_check =  np.array([4, 9, 14, 17, 19, 20, 22, 24])
incorrect_error_message = "[Marking Advice] Policy incorrect."
np.testing.assert_array_equal(policy[states_to_check], solution_policy[states_to_check], err_msg=incorrect_error_message)

# Compare state values for terminal states.
states_to_check =  np.array([18, 23])
incorrect_error_message = "[Marking Advice] Value of terminal state is not zero."
np.testing.assert_array_equal(v[states_to_check], solution_values[states_to_check], err_msg=incorrect_error_message)

Student's policy:
[['e' 'e' 'e' 'n' 'w']
 ['n' 'n' 'n' 'n' 'n']
 ['n' 'n' 'n' 'e' 'n']
 ['n' 'n' 'n' 'n' 'n']
 ['n' 'n' 'n' 'n' 'n']]
Solution policy:
[['e' 'e' 'e' 'n' 'w']
 ['n' 'n' 'n' 'n' 'n']
 ['n' 'n' 'n' 'e' 'n']
 ['n' 'n' 'n' 'n' 'n']
 ['n' 'n' 'n' 'n' 'n']]


Student's v:
[[7. 8. 9. 0. 9.]
 [6. 7. 8. 0. 8.]
 [5. 6. 7. 6. 7.]
 [4. 5. 6. 5. 6.]
 [3. 4. 5. 4. 5.]]
Solution v:
[[7. 8. 9. 0. 9.]
 [6. 7. 8. 0. 8.]
 [5. 6. 7. 6. 7.]
 [4. 5. 6. 5. 6.]
 [3. 4. 5. 4. 5.]]


## Exercise 2: Stochastic Environment

In this exercise, we introduce stochasticity into the environment. Now, the agent is not always able to execute its actions as intended.

With probability 0.8, the agent moves as intended. However, with probability 0.2, it moves in a random direction.

For example, from grid square 0, if the agent tries to move north, with probability 0.8 the action will work as intended. But with probability 0.2, the agent's motor control system will move it in a random direction (including north). So, it will randomly try to move west, east, north or south with probability 0.05 each. Notice that the total probability of moving to square 5 (as intended) is 0.8 + 0.05 = 0.85.
 
Compute the optimal policy using Value Iteration.

Your value iteration method should output two one-dimensional numpy arrays with names `policy` and `v`, as in Exercise 1.

In [ ]:
import numpy as np
def move(state,action):
    new_state=state
    if action == "n" and state < 20:
        new_state = state + 5
    elif action == "e" and state % 5 < 4:
        new_state = state + 1
    elif action == "s" and state > 4:
        new_state = state - 5
    elif action == "w" and state % 5 > 0:
        new_state = state - 1
    return new_state

theta = 1e-10
values = np.zeros(25,dtype=float)
policy = np.full(25, "", dtype=str)
rewards = np.full(25,-1,dtype=int)
rewards[23] = 9
rewards[18] = -11
posible_actions = ["n", "e", "s", "w"]
prob_moving_corr = 0.85
prob_moving_incorr = 0.05
gamma = 1
delta=np.inf
while delta>=theta:
    delta=0
    for state in range(25):
        if state != 18 and state != 23:
            v = values[state]
            max_v = -np.inf
            for action in posible_actions:
                value = 0
                for j in posible_actions:
                    new_state = move(state,j)
                    if action == j:
                        value += prob_moving_corr * (rewards[new_state]+ values[new_state])
                    else:
                        value += prob_moving_incorr * (rewards[new_state]+ values[new_state])
                if value > max_v:
                    values[state] = value
                    policy[state] = action
                    max_v = value
                    value=0
            delta = max(delta, np.abs(v - values[state]))
print(np.flip(values.reshape((5,5),),0))
print(np.flip(policy.reshape((5,5),),0))


[[5.79052626 7.14913593 8.54427725 0.         8.57073272]
 [4.6703214  5.85330784 6.30125397 0.         6.35212324]
 [3.48718058 4.55927078 4.91905831 3.11210524 4.9878853 ]
 [2.3016964  3.27294329 3.58847267 2.52899625 3.67162042]
 [1.17721846 2.06109352 2.34352258 1.46180002 2.43774151]]
[['e' 'e' 'e' '' 'w']
 ['e' 'n' 'n' '' 'n']
 ['n' 'n' 'n' 'e' 'n']
 ['n' 'n' 'n' 'e' 'n']
 ['n' 'n' 'n' 'n' 'n']]


: 

In [ ]:
import numpy as np
def move(state,action):
    new_state=state
    if action == "n" and state < 20:
        new_state = state + 5
    elif action == "e" and state % 5 < 4:
        new_state = state + 1
    elif action == "s" and state > 4:
        new_state = state - 5
    elif action == "w" and state % 5 > 0:
        new_state = state - 1
    return new_state

theta = 1e-10
values = np.zeros(25,dtype=float)
policy = np.full(25, "", dtype=str)
rewards = np.full(25,-1,dtype=int)
rewards[23] = 9
rewards[18] = -11
posible_actions = ["n", "e", "s", "w"]
prob_moving_corr = 0.85
prob_moving_incorr = 0.05
gamma = 1
delta=np.inf
while delta>=theta:
    delta=0
    for state in range(25):
        if state != 18 and state != 23:
            v = values[state]
            new_val=[]
            for action in posible_actions:
                value=0
                for j in posible_actions:
                    new_state = move(state,j)
                    if action == j:
                        value += prob_moving_corr * (rewards[new_state]+ values[new_state])
                    else:
                        value += prob_moving_incorr * (rewards[new_state]+ values[new_state])
                new_val.append(value)
            values[state] = max(new_val)
            delta = max(delta, np.abs(v - values[state]))
print(np.flip(values.reshape((5,5),),0))
print(np.flip(policy.reshape((5,5),),0))

[[6.04169329 7.28756636 8.61359951 0.         8.69262311]
 [4.86185111 5.99087587 6.37082431 0.         6.46721593]
 [3.67550938 4.69621388 4.99441863 3.2189158  5.10250988]
 [2.48699534 3.40945989 3.66922967 2.64122933 3.78610115]
 [1.35979208 2.19733672 2.42878751 1.57272161 2.55202451]]
[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']]


In [ ]:
# Please write your code for Exercise 2 in this cell or in as many cells as you want ABOVE this cell.
# Your code should compute the values of policy and v from scratch when this cell is executed, 
# using the value iteration algorithm.

# YOUR CODE HERE

In [8]:
# DO NOT DELETE OR MODIFY THIS CELL!

print("Student's v:")
print(np.flip(values.reshape((5, 5)), 0))
print("\n")
print("Student's policy:")
print(np.flip(policy.reshape((5, 5)), 0))

Student's v:
[[5.79052626 7.14913593 8.54427725 0.         8.57073272]
 [4.6703214  5.85330784 6.30125397 0.         6.35212324]
 [3.48718058 4.55927078 4.91905831 3.11210524 4.9878853 ]
 [2.3016964  3.27294329 3.58847267 2.52899625 3.67162042]
 [1.17721846 2.06109352 2.34352258 1.46180002 2.43774151]]


Student's policy:
[['e' 'e' 'e' '' 'w']
 ['e' 'n' 'n' '' 'n']
 ['n' 'n' 'n' 'e' 'n']
 ['n' 'n' 'n' 'e' 'n']
 ['n' 'n' 'n' 'n' 'n']]


## Exercise 3: Stochastic Environment with Two Pieces of Gold (6 Marks)

<img src="images/bomb and two gold.png" style="width: 300px;" align="left" caption="Figure 1"/> In this exercise, we have modified the environment presented in exercise 2. A second piece of gold has been placed on grid square 12, and a terminal state is reached only when **both** pieces of gold have been collected, or when the bomb is activated.

Compute the optimal policy for this altered environment using Value Iteration.

Your method should output two one-dimensional numpy arrays with names `policy` and `v`, as in the previous exercises. Each value in these arrays should specify the expected return and optimal policy at the corresponding grid sqaure **before any pieces of gold are collected or a bomb is activated.** 

Hint: You will need to change your state representation in order to account for the additional piece of gold.

In [17]:
import numpy as np
def move(state,action):
    new_state=state
    if action == "n" and state < 20:
        new_state = state + 5
    elif action == "e" and state % 5 < 4:
        new_state = state + 1
    elif action == "s" and state > 4:
        new_state = state - 5
    elif action == "w" and state % 5 > 0:
        new_state = state - 1
    return new_state

theta = 1e-10
values = np.zeros(75,dtype=float)
policy = np.full(75, "", dtype=str)
rewards = np.full(75,-1,dtype=float)
rewards[[12,23,12+25,23+50]] = 9
rewards[[18,18+25,18+50]] = -11
print(np.flip(rewards[:25].reshape((5, 5)), 0))
posible_actions = ["n", "e", "s", "w"]
prob_moving_corr = 0.8
prob_moving_incorr = 0.2*0.25
gamma = 1
delta=np.inf
while delta>=theta:
    delta=0
    for state in range(75):
        if state<25:
            #no gold collected
            if state != 18:
                v = values[state]
                max_v = -np.inf
                value = 0
                for action in posible_actions:
                    value=0
                    for j in posible_actions:
                        new_state = move(state,j)
                        if new_state == 23 and state ==23:
                            if action == j:
                                value += (prob_moving_corr+prob_moving_incorr) * (-1.0+ gamma* values[new_state])
                            else:
                                value += prob_moving_incorr * (-1.0+ gamma* values[new_state])
                        else:
                            if new_state == 12:
                                new_state = 12+50
                            if new_state == 23 and state !=23:
                                new_state = 23+25
                            if action == j:
                                value += (prob_moving_corr+prob_moving_incorr) * (rewards[new_state]+ gamma* values[new_state])
                            else:
                                value += prob_moving_incorr * (rewards[new_state]+ gamma* values[new_state])

                    if value > max_v:
                        max_v = value
                        policy[state] = action
                        values[state] = value
                delta = max(delta, np.abs(v - values[state]))
        elif state >=25 and state <50:
            #gold in 23 collected
            if state != 18+25 and state != 12+25:
                v = values[state]
                max_v = -np.inf
                for action in posible_actions:
                    value=0
                    for j in posible_actions:
                        new_state = move(state%25,j)+25
                        if action == j:
                            value += (prob_moving_corr+prob_moving_incorr) * (rewards[new_state]+ gamma* values[new_state])
                        else:
                            value += prob_moving_incorr * (rewards[new_state]+ gamma* values[new_state])

                    if value > max_v:
                        max_v = value
                        policy[state] = action
                        values[state] = value
                delta = max(delta, np.abs(v - values[state]))
        else:
            #gold in 12 collected
            if state != 18+50 and state != 23+50:
                v = values[state]
                max_v = -np.inf
                for action in posible_actions:
                    value=0
                    for j in posible_actions:
                        new_state = move(state%25,j)+50
                        if action == j:
                            value += (prob_moving_corr+prob_moving_incorr) * (rewards[new_state]+ gamma* values[new_state])
                        else:
                            value += prob_moving_incorr * (rewards[new_state]+ gamma* values[new_state])

                    if value > max_v:
                        max_v = value
                        policy[state] = action
                        values[state] = value
                delta = max(delta, np.abs(v - values[state]))

v=values[:25]
p=policy[:25]

[[ -1.  -1.  -1.   9.  -1.]
 [ -1.  -1.  -1. -11.  -1.]
 [ -1.  -1.   9.  -1.  -1.]
 [ -1.  -1.  -1.  -1.  -1.]
 [ -1.  -1.  -1.  -1.  -1.]]


In [ ]:
# Please write your code for Exercise 3 in this cell or in as many cells as you want ABOVE this cell.
# Your code should compute the values of policy and v from scratch when this cell is executed, 
# using the value iteration algorithm.

# YOUR CODE HERE

In [98]:
# DO NOT DELETE OR MODIFY THIS CELL!

print("Student's v:")
print(np.flip(v.reshape((5, 5)), 0))
print("\n")
print("Student's policy:")
print(np.flip(p.reshape((5, 5)), 0))

Student's v:
[[ 0.3166459   1.55792748  2.82269425  1.08255704  2.72396135]
 [ 1.02035952  2.26180583  2.93542457  0.          0.93932333]
 [ 2.10151236  3.51308265  2.45546907  2.86998968  1.53980033]
 [ 1.08518787  2.27434359  3.51711085  2.23600193  0.99804227]
 [-0.01510284  1.09771675  2.20788018  1.06112223 -0.0585907 ]]


Student's policy:
[['e' 'e' 'e' 'w' 'w']
 ['e' 's' 's' '' 'n']
 ['e' 'e' 's' 'w' 'w']
 ['e' 'e' 'n' 'w' 'w']
 ['e' 'n' 'n' 'n' 'w']]


# With dictionary


In [9]:
import numpy as np

action_names = [
    'North',
    'East',
    'South',
    'West',
]

actions = [
    np.array([1, 0]), # North
    np.array([0, 1]), # East
    np.array([-1, 0]),# South
    np.array([0, -1]),# West
]

action_abrev = [
    'n',
    'e',
    's',
    'w',
]


def print_state_dynamics(transition_dynamics, state):
    dynamics = transition_dynamics[state]
    
    print('State {}'.format(state))
    
    for action, action_dynamics in dynamics.items():
        print('\t{}'.format(action_names[action]))
        for actual_action, action_probs in action_dynamics.items():
            print('\t\t{} - {}'.format(action_names[actual_action], action_probs))

def print_transition_dynamics(transition_dynamics):
    """
    Use this function if you would like to visualise the transition dynamics.
    
    Call this function with the transition dynamics as a parameter.
    """
    for state, dynamics in transition_dynamics.items():
        print_state_dynamics(transition_dynamics, state)

In [10]:

def create_transition_dynamics(num_states, gold_states, terminal_states, bomb_states, stochasticity=1):
    action_reward = -1
    gold_reward = 10
    bomb_reward = -11
    transition_dynamics={}
    random_action_prob = (1-stochasticity)/len(actions)

    for s in range(num_states):
        state_multiplier = s//25
        state_offset = state_multiplier * 25
        offset_s = s - state_offset
        x = int(offset_s/5)
        y = int(offset_s - (x * 5))
        pos = np.array([x, y])

        action_transitions = {}

        for action in range(len(actions)):
            action_transition_dynamics = {}
            for final_direction in range(len(actions)):
                direction = actions[final_direction]
                new_position = pos + direction
                new_position = np.clip(new_position, 0, 4)

                action_probability = random_action_prob
                if action == final_direction:
                    action_probability += stochasticity

                new_state = (new_position[0] * 5) + new_position[1]
                reward=action_reward
                if new_state+state_offset in bomb_states:
                    reward += bomb_reward
                elif new_state+state_offset in gold_states and s!=new_state:
                    reward += gold_reward
                if num_states > 25:
                    if new_state+state_offset == 12:
                        new_state = 12+25
                    if new_state+state_offset == 23 and s!=23:
                        new_state = 23+50
                new_state += state_offset

                transition = (round(action_probability, 2), new_state, reward)
                action_transition_dynamics[final_direction] = transition
            action_transitions[action] = action_transition_dynamics
        transition_dynamics[s] = action_transitions
    return transition_dynamics
        

In [ ]:
num_states = 25
gold_states=[23]
terminal_states = [18,23]
